# Generated by Django 2.2.2 on 2020-02-09 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factmag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 8, 25, 31, 830497, tzinfo=utc)),
        ),
    ]
