# Generated by Django 2.2.2 on 2020-02-09 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factmag', '0002_auto_20200209_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 8, 26, 24, 301170, tzinfo=utc)),
        ),
    ]
