# Generated by Django 2.2.2 on 2020-02-11 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factmag', '0004_auto_20200210_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 4, 6, 8, 657958, tzinfo=utc)),
        ),
    ]
