# Generated by Django 2.2.2 on 2020-02-11 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factmag', '0014_auto_20200211_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 5, 34, 41, 259108, tzinfo=utc)),
        ),
    ]
