# Generated by Django 2.2.2 on 2020-02-11 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factmag', '0025_auto_20200211_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='factmag_model',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='factmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 6, 9, 2, 36823, tzinfo=utc)),
        ),
    ]
