# Generated by Django 2.2.2 on 2020-02-11 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mixmag', '0031_auto_20200211_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 10, 10, 11, 151320, tzinfo=utc)),
        ),
    ]
