# Generated by Django 2.2.2 on 2020-02-26 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mixmag', '0035_auto_20200220_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmag_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 5, 4, 48, 480081, tzinfo=utc)),
        ),
    ]
