# Generated by Django 2.2.2 on 2020-02-10 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitchfork_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=300)),
                ('headline', models.CharField(default=None, max_length=300)),
                ('description', models.CharField(default=None, max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 10, 9, 7, 6, 748099, tzinfo=utc))),
                ('tags', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
