# Generated by Django 2.2.2 on 2020-02-11 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('residentadvisor', '0002_auto_20200211_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentadvisor_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 11, 4, 15, 48, 991894, tzinfo=utc)),
        ),
    ]
